[Audio]
PreferredLanguage=jpn,jp,eng,en
Volume=85

[General]
FileDialogLastLocation=file:///home/itachi/Videos/Anime/%5BExiled-Destiny%5D Hetalia The Beautiful World
LastPlayedFile=file:///home/itachi/Videos/Anime/%5BExiled-Destiny%5D Hetalia The Beautiful World/%5BExiled-Destiny%5D_Hetalia_The_Beautiful_World_Ep02_(A1E49653).mkv
LastUrl=http://172.19.178.62:48781/Movies/English%20Movies/2016/Hacksaw%20Ridge%20%282016%29/Hacksaw.Ridge.2016__1080p.BRrip__BDPLEX.mp4
ShowHeader=false
ShowMenuBar=false
ShowPreviewThumbnail=true

[Playback]
OpenLastPlayedFile=true
RestoreFilePosition=true
SavePositionInterval=60

[Playlist]
PlaybackBehavior=StopAfterLast
RememberState=true

[Subtitles]
PreferredLanguage=eng,en

[Video]
ScreenshotFormat=png
ScreenshotTemplate=/home/itachi/Pictures/Haruna screenshots/%F-%n
