[Audio]
PreferredLanguage=jpn,jp,eng,en
Volume=15

[General]
FileDialogLastLocation=file:///home/itachi/Videos/Movies/Dark.SEASON.01.S01.COMPLETE.DUAL-AUDIO.GER-ENG.1080p.10bit.WEBRip.6CH.x265.HEVC-PSA
LastPlayedFile=file:///home/itachi/Videos/Movies/Dark.SEASON.01.S01.COMPLETE.DUAL-AUDIO.GER-ENG.1080p.10bit.WEBRip.6CH.x265.HEVC-PSA/Dark.S01E09.Everything.is.Now.DUAL-AUDIO.GER-ENG.1080p.10bit.WEBRip.6CH.x265.HEVC-PSA.mkv
LastUrl=http://172.19.178.62:48781/Movies/English%20Movies/2016/Hacksaw%20Ridge%20%282016%29/Hacksaw.Ridge.2016__1080p.BRrip__BDPLEX.mp4
ShowHeader=false
ShowMenuBar=false
ShowPreviewThumbnail=true

[Playlist]
RememberState=true
Visible=true

[Subtitles]
PreferredLanguage=eng, en

[Video]
ScreenshotFormat=png
ScreenshotTemplate=/home/itachi/Pictures/Haruna screenshots/%F-%n
