[Audio]
PreferredLanguage=jpn,jp,eng,en
Volume=75

[General]
FileDialogLastLocation=file:///home/itachi/Videos/Anime/%5BJudas%5D Claymore (Season 1) %5B1080p%5D%5BHEVC x265 10bit%5D%5BDual-Audio%5D%5BEng-Sub%5D
LastPlayedFile=file:///home/itachi/Videos/Anime/%5BJudas%5D Claymore (Season 1) %5B1080p%5D%5BHEVC x265 10bit%5D%5BDual-Audio%5D%5BEng-Sub%5D/%5BJudas%5D Claymore - 21 - Invasion of Pieta (Part 1).mkv
LastUrl=http://172.19.178.62:48781/Movies/English%20Movies/2016/Hacksaw%20Ridge%20%282016%29/Hacksaw.Ridge.2016__1080p.BRrip__BDPLEX.mp4
ShowHeader=false
ShowMenuBar=false
ShowPreviewThumbnail=true

[Playback]
OpenLastPlayedFile=true
RestoreFilePosition=true
SavePositionInterval=60

[Playlist]
PlaybackBehavior=StopAfterLast
RememberState=true

[Subtitles]
PreferredLanguage=eng,en

[Video]
ScreenshotFormat=png
ScreenshotTemplate=/home/itachi/Pictures/Haruna screenshots/%F-%n
